const secretQuestions = [
  "What was the name of your first pet?",
  "In which city were you born?",
  "What is your mother's maiden name?",
  "What was the make of your first car?",
  "What is the name of the street you grew up on?",
  "What was the name of your elementary school?",
  "What is your favorite book?",
  "What is the name of your favorite childhood friend?",
  "What is your favorite movie?",
  "What was your childhood nickname?",
  "What is the name of the hospital where you were born?",
  "What is your father's middle name?",
  "What was the name of your first grade teacher?",
  "What was your high school mascot?",
  "What is the name of the company where you had your first job?",
  "What is your favorite color?",
  "What is the name of your favorite childhood teacher?",
  "What is your favorite sports team?",
  "What is the middle name of your oldest child?",
  "What is the name of your favorite childhood toy?",
  "In what city did your parents meet?",
  "What is the name of your favorite restaurant?",
  "What is your favorite holiday destination?",
  "What was the first concert you attended?",
  "What is the name of your favorite fictional character?",
  "What is the name of the street your best friend in high school lived on?",
  "What is your grandmother's first name?",
  "What was the name of your first boss?",
  "What is the name of the park nearest to your childhood home?",
  "What is the name of your favorite childhood book?"
];

module.exports = secretQuestions;
